version: '1'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    image: wolf7201/foodgram_backend
    env_file: .env
    volumes:
      - static_foodgram:/backend_static/
      - media_foodgram:/app/media
    depends_on:
      - db
  frontend:
    image: wolf7201/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_foodgram:/frontend_static/
  gateway:
    image: wolf7201/foodgram_gateway
    depends_on:
      - backend
    volumes:
      - static_foodgram:/static/
      - media_foodgram:/media
    ports:
      - 8000:80