# Generated by Django 3.2 on 2023-10-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
